---
title: "Market Basket"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##tuff

Checkout: Leave master branch at latest version, move working directory to specified commit

Reset: Move master and working directory.

Revert: Less harsh version of reset, maintains commit history but moves forward by one from most recent commit.

git init, git add to stage, git rm --cached <file> to unstage. Git diff, git checkout, 
echo ".DS_Store"> .gitignore// Ignore common OSX file.

GIT
git add -u: add modified files.
List files: ls
git checkout
Create New File: touch file.ext
Clones repo into current directory: git clone repo_url
Check remote connections: git remote -v
Stage files for commiting: git add . #adds all changed/new files
git add filename.ext #adds single file
Commit changes/new files: git commit -m "Commit message"
See change log: git log
Add upstream to update a forked repo with the original: remote add upstream repo_url 
Update chnages from original repo, put in new branch: git fetch upstream
Merge the upstream chnages to master on your local machine. Nos push them up if you want.
git merge upstream/master
Update local repo with master changes: git pull origin master

Pull Request
Asking someone to take up changes you made + go to personal repo + submit a pull request
trying to commit to upstream repo

Other
git remote + git help add + git init + git add *.py + to ignore creat .gitignore
git diff (--cache) + git rm t.py + git rm --cached 't.py' //remove from staging area
change name: git rename origin newname + tagging: git tag + create: git tag -a sometagname
git show version_name + git branch (--merged, --no-merged) + git merge fix20
never rebase commits to public repo + rebase: branch working with behind in commit
use revert (change commit and log the change) + dont use reset: erases commit and doesnt log.
git revert HEAD + git reset HEAD + git clean -n: never use clean + generate ssh:
generate multiple github accounts using diff ssh keys

Fork and Pull
get fork url use: git clone url + git remote add upstream url: ref original repo
git fetch upstream: pull changes fro original repo + git push origin master: push stuff to clone
git merge upstream/master: merge github and local + make pull request, send pull request

import -> tidy -> Explore [ transform <-> visualize <-> model ] -> communicate

matplotlib: rcparams set global parameters, isin and crosstab functions pandas
%matplotlib notebook: interactive plots
Python memory storage: use pd.copy to create a deep copy instead of a shallow copy
use help or any in Ipy to bring up docs
pd.DatetimeIndex, grouped.unstack()
select_dtypes pandas

%who or %whos shows defined variables. %reset resets them.
%run script.py: func? prints out func doc
a[::2]: gives every even valued index in array.
q is the debugger in IPy

Append dict to df, use ignore_index = True: films_df = films_df.append(film_dict, ignore_index=1)
%debug, interact IPy also use as decorator
np: fromfile, genfromtxt

Dictionary: keys (strings)-values(list) makes Dataframe: keys(cols)-values(rows)
state.reset_index(level = 0, inplace = True)

import pdb; pdb.set_trace(), sklearn.metrics.silhouette_samples
import sqlite3 + con = sqlite3.connect(':memory:')

print(sessionInfo()); suppressPackageStartupMessages(library(ggmap)) 
rm(objectlist): Remove one or more objects from the workspace; rm(list = ls()): Remove all objects in the current workspace
The cut() function used to transform a numeric variable into a categorical variable.
vec = rep(c(0,1), c(4,6)) + vec_fac = factor(vec, labels=c('male','female')
Funcs: tail, levels, list.files(), as.Date, na.omit, all/any, xor, unlist, attributes(), names() na.strings = "", cor.test, is.na, complete.cases
Key words: stop, invisible, and warning, recall (for recursion)
Function(x) sd(x)/mean(x): equivalent of lambda functions In Python.
Library(): shows currently installed packages.
identify(), pairs(), par(), by(), grid.arrange(), do.call, with, .libPaths() 
installr: update r in windows, stringi, dt: data table in R; RColorBrewer, gmodels R, scales R, GGally, scales, memisc, lattice, MASS, car, reshape gridextra
packages: stringr, dbi, rodbc, RSQLite, RCurl, car: recode (good for dummying)

Nested CV: 5 x 5

gs = GridSearchCV(estimator = pipe_svc, param)grid = param_grid, scoring = 'accuracy', cv = 5)
scores = cross_val_score(gs, X, y, scoring = 'accuracy', cv = 5)


Algorithms for Personalization: Linear/Logistic/Elastic Net Regression, Restricted Boltzmann Machines, Singular Value Decomposition, Makov Chains, 
Latent Dirichlet Allocation, Association Rules, Gradient Boosted Decision Trees, Random Forests, Affinity Propagation, K-Means, Matix Factorization, 
Alternating Least Squares.



