# Distributed

ff | bigmemory | biganalytics | bigtabulate | purrrlyr: dplyr purrr | furrr: parallelized purrr

foreach + doMC | parallel | doParallel

Out-of-Core: pandas chunksize Semantic Style Transfer symbolic regression

## PySpark

* A [cheatsheet[(https://www.qubole.com/resources/pyspark-cheatsheet/).

* Spark's assumes the target is called 'label' in ML. Everything else is a feature.

* alias() method to rename a column you're selecting.

* cast() method: nominative determinism on columns

* withColumn(): create new column

* pyspark.ml.feature

* At the core of the pyspark.ml module are the Transformer and Estimator classes. Transformer classes are used for pre-processing and have a .transform() method. eg. PCA

* You can create what are called 'one-hot vectors' to represent the carrier and the destination of each flight. A one-hot vector is a way of representing a categorical feature where every observation has a vector in which all elements are zero except for at most one element, which has a value of one (1).

* Estimator classes are for modeling and all implement a .fit() method. eg. StringIndexerModel for including categorical data saved as strings in your models

* selectExpr() takes SQL expressions as a string

* show() vs collect()

* Spark only handles numeric data

* In Spark it's important to make sure you split the data after all the transformations. This is because operations like StringIndexer don't always produce the same index even when given the same list of strings.

## sparklyr

* To collect your data: that is, to move it from Spark to R, you call collect(). copy_to() moves your data from R to Spark.

* Use compute() to compute the calculation, but store the results in a temporary data frame on Spark.

* If you want to delay returning the data, you can use dbSendQuery() to execute the query, then dbFetch() to return the results.

* feature transforms: ft_, ml functions: ml_, spark df functions: sdf_

* ft_tokenizer(): to lower and split into individual words, ft_regex_tokenizer, sdf_sort


