# Code Notes

## Python

### General

* https://chrisalbon.com/

* pandas: isin | crosstab

* pd.group_by aggregate functions: size, count, sum, mean, median, sd, var, min, max, prod, first, last

* The only float that isn't equal to itself is nan.

* %matplotlib notebook: interactive plots

* Memory storage: use pd.copy to create a deep copy instead of a shallow copy

* IPy: %who or %whos shows defined variables & %reset resets them

* Append dict to df: use ignore_index = True. eg. films_df = films_df.append(film_dict, ignore_index=1)

* Debugging: import pdb | pdb.set_trace(), 

* dir() gives a list of in scope variables

* globals() gives a dictionary of global variables

* locals() gives a dictionary of local variables

* https://bugra.github.io/work/notes/2015-01-03/i-wish-i-knew-these-things-when-i-first-learned-python/

* np.dot = np.multiply %>% np.sum

* flatten dict

    * pd.io.json.json_normalize(stuff)
    *https://stackoverflow.com/questions/6027558/flatten-nested-python-dictionaries-compressing-keys/41689055#41689055
    * https://towardsdatascience.com/flattening-json-objects-in-python-f5343c794b10
    
### Vanderplas Jupyter

* create helper functions and units tests as R/py for Rmd/ipynb

* pytest/hypothesis for testing

* use makefile to run cmd commands

* Write file with date: df.to_csv('{}_model.csv'.format(str(datetime.datetime.now()).split(' ')[0]))

* Make package for workflow with data (__init__.py) and use this formation for function docs:

```{python, eval = FALSE}
def fun(a):

  #Role
  #-----
  #Does something
  
  #Parameters
  #---------
  #Accepts something
  
  #Returns
  #-------
  #Returns something
  
  return(a)
```

## R

### General

* ctrl + shift + a: reformat code in rstudio

* library(rethinking) | data(UCBadmit) | d <- UCBadmit

* purrr::p/map_dfr/c

* date = date %>% as.POSIXct() %>% strptime('%Y-%m-%d') %>% strftime(format="%Y-%m-%d")

* e <- matrix(NA_real_, nrow = 1000, ncol = 8)

* rowwise in R: purrr::pmap

* str_split + unnest()

* https://stat.ethz.ch/R-manual/R-devel/library/base/html/Last.value.html

* na_if: Replace certain values by na

* purrr::map_df - map over columns

* studio multiple cursors, snippets,  addins

* ctrl + shift + o: toggle table of contents

* ctrl shift enter: run chunk

* ctrl pageup/down: navigate chunks

* atl shift k: shortcuts

* ctrl + shift + R: label sections

* ctrl + alt + R: run all chunks

* df_print: kable in yaml rmrkdown header

* rm(list = ls()): Remove all objects in the current workspace

* cut(): Transform a numeric variable into a categorical variable.

* car: recode (good for dummying)

* Examine the objects in the workspace: ls.str()

* This is how you dynamically update a value in Rmarkdown: x = *backtick* r x *backtick*. 

* df[setdiff(names(df), "z")]: remove column z

* purrr::walk

* purr::keep/discard for is.factor

* choroplethr | choroplethrMaps || d3r | d3treeR | data.tree

### Knitting A GHub Doc

output:
  github_document: default
  html_notebook: default
  
## Various

```{r, eval = F}
tapply(Summary_Variable, Group_Variable, Function)

boxplot(frequency ~ attitude*gender,
col=c("white","lightgray"), politeness)

#corrplot package in r
cor(Carseats[sapply(Carseats, function(x) !is.factor(x))])

install.packages(c("caret", "pROC"), dependencies = c("Depends", "Imports", "Suggests"))

library(knitr)
kable(pause_sum, caption = "Summary Statistics Table for Exit Slip Dataset",
      col.names = c("Mean", "Median", "SD", "Min", "Max", "N", "NAs"))

typeof(1) #"double"
typeof(1L) #"integer"

#Prints out the first 4 multiples of 3.
for(i in 1:4*3) {cat(i)}
```
