---
title: "Placeholder"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## General

[Optimal Bins For Histogram](https://stats.stackexchange.com/questions/798/calculating-optimal-number-of-bins-in-a-histogram/862#862)

**The Coefficient of Unalikeability**: (Unalikeability is defined as how often observations differ from one another). It varies from 0 to 1. The higher the value, the more unalike the data are.

## SQL

* Standard sql commands: Select, From, Insert, Update, Delete, Create, Drop, Truncate

* Joins: ‘left’, ‘right’, ‘inner’, ‘full’, and ‘union’

* Differences between null vs. 0

* A schema is a blueprint for storing data. For a table every row has same number of columns, and each column is of the same type.

## Missingness & Imputation

* Missingness types: 1) Completely at Random, 2) At Random, 3) Not at random

The pros of imputation:

* Helps retain a larger sample size of your data.

* Does not sacrifice all the available information in an observation because of sparse missingness.

* Can potentially avoid unwanted bias.

The cons of imputation:

* The standard errors of any estimates made during analyses following imputation can tend to be too small.

* The methods are under the assumption that all measurements are actually “known,” when in fact some were imputed.

* Can potentially induce unwanted bias.

* dplyr::case_when

* mean of each column = df .mean(axis = 0)  || df .mean(axis = 'index' ) 

* mean of each row = df .mean(axis = 1)  || df .mean(axis = 'columns' ) 

##Data Table

dt[i, j, by] : subset by i calculate by j grouped using by